Repository WannaReact/wondu-market, pull requests merged in 2022-04, with the labels that each got.

#66 Inputs 수정
  src/components/Inputs/index.tsx
  src/components/Inputs/styled.ts
Labels: 버그 수정, 기능 수정

#70 API 수정 및 삭제
  lib/mongoose/createHandler.ts
  lib/mongoose/dbConnect.ts
  lib/mongoose/models/Category.ts
  lib/mongoose/models/Comment.ts
  lib/mongoose/models/Coupon.ts
  lib/mongoose/models/CouponType.ts
  lib/mongoose/models/Courier.ts
  lib/mongoose/models/Inquiry.ts
  lib/mongoose/models/Order.ts
  lib/mongoose/models/Product.ts
  lib/mongoose/models/Review.ts
  lib/mongoose/models/User.ts
  lib/mongoose/models/constants.ts
  lib/mongoose/response.ts
  src/pages/api-test/utils.ts
  src/pages/api/category/[id].ts
  src/pages/api/category/index.ts
  src/pages/api/comment/index.ts
  src/pages/api/coupon/index.ts
  src/pages/api/coupon/type/[id].ts
  src/pages/api/coupon/type/index.ts
  src/pages/api/courier/[name].ts
  src/pages/api/courier/index.ts
  src/pages/api/inquiry/answer/[id].ts
  src/pages/api/inquiry/index.ts
  src/pages/api/order/[id].ts
  src/pages/api/order/index.ts
  src/pages/api/product/[id].ts
  src/pages/api/product/index.ts
  src/pages/api/review/index.ts
  src/pages/api/user/index.ts
Labels: 기능 수정

#72 API 요청시 ReferenceError가 발생하는 버그 수정
  lib/mongoose/models/CouponType.ts
  lib/mongoose/models/Order.ts
  lib/mongoose/models/Product.ts
Labels: 버그 수정

#73 API 수정
  lib/mongoose/models/Comment.ts
  lib/mongoose/models/Coupon.ts
  lib/mongoose/models/CouponType.ts
  lib/mongoose/models/Inquiry.ts
  lib/mongoose/models/Order.ts
  lib/mongoose/models/Product.ts
  lib/mongoose/models/Review.ts
  lib/mongoose/models/User.ts
  lib/mongoose/models/constants.ts
  src/pages/api/comment/[id].ts
  src/pages/api/comment/index.ts
  src/pages/api/coupon/[id].ts
  src/pages/api/coupon/index.ts
  src/pages/api/coupon/type/[id].ts
  src/pages/api/coupon/type/index.ts
  src/pages/api/courier/[name].ts
  src/pages/api/courier/index.ts
  src/pages/api/inquiry/[id].ts
  src/pages/api/inquiry/answer/[id].ts
  src/pages/api/inquiry/index.ts
  src/pages/api/order/[id].ts
  src/pages/api/order/index.ts
  src/pages/api/product/[id].ts
  src/pages/api/product/index.ts
  src/pages/api/review/[id].ts
  src/pages/api/review/index.ts
  src/pages/api/user/[id].ts
  src/pages/api/user/index.ts
Labels: 기능 추가, 기능 수정

#74 Fix/api
  .eslintrc.json
  lib/mongoose/models/Comment.ts
  lib/mongoose/models/Inquiry.ts
  lib/mongoose/models/Order.ts
  lib/mongoose/models/Product.ts
  lib/mongoose/models/Review.ts
  lib/mongoose/models/User.ts
  package.json
  src/pages/api-test/utils.ts
  src/pages/api/comment/[id].ts
  src/pages/api/coupon/[id].ts
  src/pages/api/inquiry/[id].ts
  src/pages/api/order/[id].ts
  src/pages/api/product/[id].ts
  src/pages/api/review/[id].ts
  src/pages/api/user/index.ts
  yarn.lock
Labels: 기능 추가, 세팅, 기능 수정

#75 tinyMCE 적용 및 커스텀 셀렉트 박스 구현
  components/AddProduct/EditorModal.tsx
  components/AddProduct/ImgSlide.tsx
  components/SelectBox/index.tsx
  components/SelectBox/styled.ts
  components/layouts/SellerLayout.tsx
  pages/addproduct/index.tsx
  public/images/icon-Triangle-down.png
  public/images/icon-Triangle-up.png
Labels: 기능 추가, 기능 수정

#76 Fix/tosrc
  components/layouts/SellerLayout.tsx
  components/layouts/styled.ts
  components/seller/ClaimProduct.tsx
  components/seller/OrderCheck.tsx
  components/seller/QuestionTr.tsx
  components/seller/Questions.tsx
  components/seller/ReviewTr.tsx
  components/seller/Reviews.tsx
  components/seller/SellPropduct.tsx
  components/seller/TrackingInfo.tsx
  components/seller/styled.ts
  pages/addproduct/index.tsx
  pages/seller/[menu].tsx
  pages/seller/index.tsx
  src/components/AddProduct/EditorModal.tsx
  src/components/AddProduct/ImgSlide.tsx
  src/components/SelectBox/index.tsx
  src/components/SelectBox/styled.ts
  src/components/layouts/SellerLayout.tsx
  src/components/seller/QuestionTr.tsx
  src/components/seller/ReviewTr.tsx
  src/components/seller/SellPropduct.tsx
  src/pages/addproduct/index.tsx
Labels: 리팩토링, 기능 수정

#77 unit이 있는 Input에 숫자 포맷팅 추가
  src/components/Inputs/index.tsx
Labels: 기능 추가

#79 반응형 미지원 및 DefaultContainer 추가
  package.json
  src/components/NavBar/SearchBar/styled.ts
  src/components/NavBar/index.tsx
  src/components/NavBar/styled.ts
  src/components/common/DefaultContainer/index.tsx
  src/components/common/DefaultContainer/styled.ts
  src/hooks/useBreakpoint.ts
  src/shared/constants.ts
  yarn.lock
Labels: 기능 수정

#63 Feature/validation
  components/ProductCard/index.tsx
  components/ProductCard/styled.ts
  pages/_app.tsx
  pages/_document.tsx
  pages/buttons.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/login/styled.ts
  src/components/Buttons/index.tsx
  src/components/Buttons/styled.ts
  src/components/Inputs/index.tsx
  src/components/Inputs/styled.ts
  src/pages/join/index.tsx
  src/pages/join/styled.ts
  src/pages/login/index.tsx
  src/pages/login/styled.ts
Labels: 기능 추가, 리팩토링

#82 Coupon, CouponType API 삭제
  lib/mongoose/dbConnect.ts
  lib/mongoose/models/Coupon.ts
  lib/mongoose/models/CouponType.ts
  lib/mongoose/models/Order.ts
  lib/mongoose/models/User.ts
  src/pages/api-test/utils.ts
  src/pages/api/coupon/[id].ts
  src/pages/api/coupon/index.ts
  src/pages/api/coupon/type/[id].ts
  src/pages/api/coupon/type/index.ts
  src/pages/api/order/[id].ts
  src/pages/api/order/index.ts
Labels: 기능 수정

#84 Input 컴포넌트 버그 수정
  src/components/Inputs/index.tsx
Labels: 버그 수정

#86 Feature/product details
  src/components/CommentItem/styled.ts
  src/components/CommentList/index.tsx
  src/components/CommentList/styled.ts
  src/components/QnaItem/index.tsx
  src/components/QnaItem/styled.ts
  src/components/QnaList/dummyQuestionData.json
  src/components/QnaList/index.tsx
  src/components/QnaList/styled.ts
  src/components/index.ts
  src/pages/products/[id]/index.tsx
  src/styles/GlobalStyle.ts
Labels: 기능 추가

#90 장바구니 API 추가 및 기타 API 수정
  lib/mongoose/models/Order.ts
  lib/mongoose/models/Product.ts
  lib/mongoose/models/User.ts
  src/pages/api-test/utils.ts
  src/pages/api/cart/[id].ts
  src/pages/api/comment/[id].ts
  src/pages/api/inquiry/[id].ts
  src/pages/api/order/index.ts
  src/pages/api/user/[id].ts
Labels: 기능 추가, 기능 수정

#93 레이아웃 리팩토링
  src/components/Buttons/styled.ts
  src/components/Menu/index.tsx
  src/components/Menu/styled.ts
  src/components/NavBar/styled.ts
  src/components/Table/Product.tsx
  src/components/Table/Table.tsx
  src/components/Table/TableRow.tsx
  src/components/Table/styled.ts
  src/components/common/DefaultContainer/styled.ts
  src/components/layouts/SellerLayout.tsx
  src/components/layouts/styled.ts
  src/components/seller/ClaimProduct.tsx
  src/components/seller/OrderCheck.tsx
  src/components/seller/QuestionTr.tsx
  src/components/seller/Questions.tsx
  src/components/seller/ReviewTr.tsx
  src/components/seller/Reviews.tsx
  src/components/seller/SellPropduct.tsx
  src/components/seller/TrackingInfo.tsx
  src/layouts/MenuPageLayout/index.tsx
  src/layouts/MenuPageLayout/styled.ts
  src/pages/addproduct/index.tsx
  src/pages/addproduct/styled.ts
  src/pages/seller/[menu].tsx
  src/shared/constants.ts
Labels: 리팩토링, 기능 수정

#95 폰트 깜빡임 현상 수정
  next.config.js
  package.json
  src/pages/_app.tsx
  src/styles/GlobalStyle.ts
  src/styles/font.css
  yarn.lock
Labels: 버그 수정

#96 css-loader 제거
  next.config.js
  package.json
  yarn.lock
Labels: 버그 수정

#97 discount를 discountRate로 변경
  lib/mongoose/constants.ts
  lib/mongoose/models/Order.ts
  lib/mongoose/models/Product.ts
  lib/mongoose/models/Review.ts
  lib/mongoose/models/User.ts
  src/pages/api-test/utils.ts
  src/pages/api/product/[id].ts
  src/pages/api/product/index.ts
Labels: 기능 수정

#87 API get,post 구현
  src/pages/join/index.tsx
Labels: 버그 수정, 기능 추가, 기능 수정

#102 menuPageLayout 적용 및 카테고리 수정
  src/components/AddProduct/AddProduct.tsx
  src/components/AddProduct/Header.tsx
  src/components/AddProduct/styled.ts
  src/layouts/MenuPageLayout/index.tsx
  src/pages/addproduct/index.tsx
  src/pages/seller/[menu].tsx
Labels: 기능 추가, 기능 수정

#107 API 리팩토링
  lib/mongoose/middlewares/dbConnect.ts
  lib/mongoose/middlewares/initLocals.ts
  lib/mongoose/middlewares/pagination.ts
  lib/mongoose/models/CartItem.ts
  lib/mongoose/models/Comment.ts
  lib/mongoose/models/Inquiry.ts
  lib/mongoose/models/Order.ts
  lib/mongoose/models/Product.ts
  lib/mongoose/models/Review.ts
  lib/mongoose/models/User.ts
  lib/mongoose/mongoose.d.ts
  lib/mongoose/utils/createHandler.ts
  lib/mongoose/utils/orderNumGen.ts
  lib/mongoose/utils/response.ts
  src/pages/api-test/utils.ts
  src/pages/api/cart/[id].ts
  src/pages/api/cart/index.ts
  src/pages/api/comment/[id].ts
  src/pages/api/comment/index.ts
  src/pages/api/inquiry/[id].ts
  src/pages/api/inquiry/answer/[id].ts
  src/pages/api/inquiry/index.ts
  src/pages/api/order/[id].ts
  src/pages/api/order/index.ts
  src/pages/api/product/[id].ts
  src/pages/api/product/index.ts
  src/pages/api/review/[id].ts
  src/pages/api/review/comment/[id].ts
  src/pages/api/review/index.ts
  src/pages/api/user/[id].ts
  src/pages/api/user/cart/[id].ts
  src/pages/api/user/id/index.ts
  src/pages/api/user/index.ts
  src/pages/api/user/inquiry/[id].ts
  src/pages/api/user/order/[id].ts
  src/pages/api/user/review/[id].ts
  src/pages/api/user/unique/index.ts
Labels: 기능 추가, 리팩토링, 기능 수정

#109 상품의 리뷰와 문의를 조회하는 API 분리
  lib/mongoose/constants.ts
  src/pages/api-test/utils.ts
  src/pages/api/product/[id].ts
  src/pages/api/product/inquiry/[id].ts
  src/pages/api/product/review/[id].ts
Labels: 기능 추가, 기능 수정

#110 마이페이지, 관리자페이지 API 추가
  lib/mongoose/models/User.ts
  lib/mongoose/utils/createHandler.ts
  src/pages/api-test/utils.ts
  src/pages/api/inquiry/index.ts
  src/pages/api/myPage/[id].ts
  src/pages/api/sellerPage.ts
Labels: 기능 추가, 기능 수정

#111 장바구니 페이지 구현
  public/images/icon-delete.png
  src/components/Cart/CartItem.tsx
  src/pages/cart/index.tsx
Labels: 리팩토링, 기능 수정

#114 Modal 컴포넌트화 구현
  src/components/Modals/index.tsx
  src/pages/modals.tsx
Labels: 기능 추가, 기능 수정

#119 로그인 기능 구현
  lib/mongoose/models/User.ts
  lib/mongoose/utils/response.ts
  package.json
  src/pages/_app.tsx
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/login/index.ts
  src/pages/api/user/index.ts
  src/pages/login/index.tsx
  yarn.lock
Labels: 기능 추가, 기능 수정

#120 여러 개의 상품을 한 번의 요청으로 주문할 수 있도록 API 변경
  lib/mongoose/middlewares/dbConnect.ts
  lib/mongoose/models/Order.ts
  lib/mongoose/models/OrderGroup.ts
  src/pages/api/order/[id].ts
  src/pages/api/order/index.ts
  src/pages/api/user/order/[id].ts
Labels: 기능 수정

#121 관리자 계정 추가
  src/pages/api/auth/[...nextauth].ts
  src/pages/api/login/index.ts
Labels: 기능 추가

#123 Feature/order
  package-lock.json
  package.json
  public/images/icon-delete.svg
  src/components/Portal/index.tsx
  src/components/Postcode/index.tsx
  src/components/Postcode/styled.ts
  src/components/index.ts
  src/pages/_document.tsx
  src/pages/order/index.tsx
  src/pages/order/styled.ts
  src/pages/products/[productId]/index.tsx
  yarn.lock
Labels: 기능 추가

#124 GlobalNavBar 수정
  public/images/icon-shopping-bag.svg
  src/components/NavBar/index.tsx
  src/components/NavBar/styled.ts
Labels: 기능 추가, 기능 수정

#126 gnb options로 제목을 설정하면 메뉴가 보이지 않도록 변경
  src/components/NavBar/index.tsx
Labels: 기능 수정

#129 API 변경
  lib/mongoose/models/OrderGroup.ts
  lib/mongoose/models/Product.ts
  lib/mongoose/models/Review.ts
  lib/mongoose/models/User.ts
  src/pages/api-test/utils.ts
  src/pages/api/product/[id].ts
  src/pages/api/product/index.ts
  src/pages/api/product/inquiry/[id].ts
  src/pages/api/product/review/[id].ts
  src/pages/api/review/comment/[id].ts
  src/pages/api/user/cart/[id].ts
  src/pages/api/user/inquiry/[id].ts
  src/pages/api/user/order/[id].ts
  src/pages/api/user/review/[id].ts
  src/pages/myPage/constants.tsx
Labels: 기능 수정

#131 모달 수정
  src/components/Modals/CustomModal/Contents/ConfirmOrder/index.tsx
  src/components/Modals/CustomModal/Contents/ConfirmOrder/styled.ts
  src/components/Modals/CustomModal/Contents/Result/styled.ts
Labels: 기능 수정

#130 주문 등록 및 삭제시 해당 상품의 재고량을 확인하도록 변경
  src/pages/api/order/[id].ts
  src/pages/api/order/index.ts
Labels: 기능 수정

#133 장바구니 페이지 API 연결 및 기능 구현
  src/components/Cart/CartItem.tsx
  src/components/Cart/styled.ts
  src/pages/cart/index.tsx
  src/pages/cart/styled.ts
Labels: 기능 추가, 리팩토링, 기능 수정

#134 리뷰 모달 추가
  lib/mongoose/constants.ts
  src/components/Inputs/index.tsx
  src/components/Inputs/styled.ts
  src/components/Modals/CustomModal/Contents/ConfirmOrder/index.tsx
  src/components/Modals/CustomModal/Contents/Review/index.tsx
  src/components/Modals/CustomModal/Contents/Review/styled.ts
  src/components/Table/Status/index.tsx
Labels: 버그 수정, 기능 추가, 기능 수정

#135 Feature/product details
  package.json
  src/components/CommentItem/index.tsx
  src/components/CommentList/index.tsx
  src/components/CommentList/styled.ts
  src/components/ReviewItem/index.tsx
  src/components/TabMenu/index.tsx
  src/pages/order/styled.ts
  src/pages/product/[productId]/index.tsx
  src/pages/product/[productId]/styled.ts
  src/pages/products/[productId]/index.tsx
  src/shared/types.ts
  yarn.lock
Labels: 기능 추가, 기능 수정

#136 리뷰 데이터 컴포넌트 추가
  src/components/Inputs/index.tsx
  src/components/Modals/CustomModal/Contents/EditReview/index.tsx
  src/components/Modals/CustomModal/Contents/EditReview/styled.ts
  src/components/Modals/CustomModal/Contents/PostReview/index.tsx
  src/components/Modals/CustomModal/Contents/PostReview/styled.ts
  src/components/Table/Review/index.tsx
  src/components/Table/Review/styled.ts
  src/pages/myPage/constants.tsx
  src/shared/types.ts
Labels: 기능 추가, 기능 수정
