Repository WannaReact/wondu-market, pull requests merged in 2022-03, with the labels that each got.

#11 Feature/product details
  pages/products/[id]/index.tsx
  pages/products/[id]/styled.ts
  public/images/product-img-lg.png
  styles/GlobalStyle.ts
Labels: 기능 추가

#17 Styled Buttons 변수명 변경 및 import 방식 변경에 따른 적용
  components/Buttons/index.tsx
  components/Buttons/styled.ts
Labels: 리팩토링

#18 Input 컴포넌트 추가
  components/Inputs/index.tsx
  components/Inputs/styled.ts
  components/index.ts
  components/utils/ImageWrapper.ts
  public/images/icon-check.svg
  shared/constants.ts
  styles/GlobalStyle.ts
Labels: 기능 추가

#19 Buttons 컴포넌트 중 L, M, MS, S 를 Custom 하나로 통합
  components/Buttons/index.tsx
  components/Buttons/styled.ts
  pages/buttons.tsx
  pages/index.tsx
Labels: 리팩토링

#22 Input 컴포넌트 수정
  components/Inputs/index.tsx
  components/Inputs/styled.ts
Labels: 기능 추가, 리팩토링

#14 Feature/login
  components/ProductCard/index.tsx
  components/ProductCard/styled.ts
  pages/api/dummyData.json
  pages/index.tsx
Labels: 기능 추가

#25 Feature/login 로그인 UI 완성
  components/Inputs/index.tsx
  pages/join.tsx
  pages/login.tsx
  pages/login/index.tsx
  pages/login/styled.ts
  public/images/logo.svg
  styles/GlobalStyle.ts
Labels: 기능 추가, 리팩토링

#30 GlobalNavBar 드롭다운 메뉴 UI 변경
  components/NavBar/MenuItem/index.tsx
  components/NavBar/MenuItem/styled.ts
  components/NavBar/NavButton/index.tsx
  components/NavBar/SearchBar/index.tsx
  components/NavBar/index.tsx
  components/NavBar/menuItems.ts
  components/NavBar/styled.ts
  pages/_app.tsx
  pages/index.tsx
  shared/constants.ts
Labels: 기능 추가, 리팩토링, 기능 수정

#33 Feature/login 이메일 추가 및 UI 일부 수정
  components/Inputs/index.tsx
  components/Inputs/styled.ts
  pages/join/index.tsx
  pages/login/index.tsx
Labels: 기능 추가, 리팩토링

#34 User, Review, Product, Comment API 추가
  lib/mongoose/createHandler.ts
  lib/mongoose/dbConnect.ts
  lib/mongoose/response.ts
  models/Comment.ts
  models/Product.ts
  models/Review.ts
  models/User.ts
  package.json
  pages/api-test/index.tsx
  pages/api-test/styled.ts
  pages/api/comment/[id].ts
  pages/api/comment/index.ts
  pages/api/hello.ts
  pages/api/product/[id].ts
  pages/api/product/index.ts
  pages/api/review/[id].ts
  pages/api/review/index.ts
  pages/api/user/[id].ts
  pages/api/user/index.ts
  utils/api.ts
  yarn.lock
Labels: 기능 추가

#35 API OverwriteModelError 버그 수정
  .eslintrc.json
  lib/mongoose/createHandler.ts
  lib/mongoose/dbConnect.ts
  lib/mongoose/mongoose.d.ts
  tsconfig.json
Labels: 버그 수정

#37 Fix/api
  .eslintignore
  .eslintrc.json
  models/Comment.ts
  models/Product.ts
  models/Review.ts
  models/User.ts
  models/constants.ts
  pages/api-test/index.tsx
  pages/api-test/styled.ts
  pages/api-test/utils.ts
  pages/api/comment/[id].ts
  pages/api/comment/index.ts
  pages/api/product/[id].ts
  pages/api/product/index.ts
  pages/api/review/[id].ts
  pages/api/review/index.ts
  pages/api/user/[id].ts
  pages/api/user/id/index.ts
  pages/api/user/index.ts
Labels: 버그 수정, 기능 추가, 리팩토링, 세팅, 기능 수정

#40 TextInputBox에 type, unit 옵션 추가
  components/Inputs/index.tsx
  components/Inputs/styled.ts
  pages/component-test/index.tsx
Labels: 기능 추가, 기능 수정

#38 Feature/login
  components/Inputs/index.tsx
  components/Inputs/styled.ts
  package.json
Labels: 세팅

#44 🎨 폴더구조 root -> src subset 구조로 변경
  src/components/Buttons/index.tsx
  src/components/Buttons/styled.ts
  src/components/Inputs/index.tsx
  src/components/Inputs/styled.ts
  src/components/NavBar/MenuItem/index.tsx
  src/components/NavBar/MenuItem/styled.ts
  src/components/NavBar/NavButton/index.tsx
  src/components/NavBar/NavButton/styled.ts
  src/components/NavBar/SearchBar/index.tsx
  src/components/NavBar/SearchBar/styled.ts
  src/components/NavBar/index.tsx
  src/components/NavBar/menuItems.ts
  src/components/NavBar/styled.ts
  src/components/ProductCard/index.tsx
  src/components/ProductCard/styled.ts
  src/components/ReviewItem/index.tsx
  src/components/ReviewItem/styled.ts
  src/components/StarRating/index.tsx
  src/components/index.ts
  src/components/layouts/SellerLayout.tsx
  src/components/layouts/styled.ts
  src/components/seller/ClaimProduct.tsx
  src/components/seller/OrderCheck.tsx
  src/components/seller/QuestionTr.tsx
  src/components/seller/Questions.tsx
  src/components/seller/ReviewTr.tsx
  src/components/seller/Reviews.tsx
  src/components/seller/SellPropduct.tsx
  src/components/seller/TrackingInfo.tsx
  src/components/seller/styled.ts
  src/hooks/useBreakpoint.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/addproduct/index.tsx
  src/pages/api/dummyData.json
  src/pages/api/hello.ts
  src/pages/buttons.tsx
  src/pages/findLogin/index.tsx
  src/pages/index.tsx
  src/pages/join/index.tsx
  src/pages/join/styled.ts
  src/pages/login/index.tsx
  src/pages/login/styled.ts
  src/pages/products/[id]/index.tsx
  src/pages/products/[id]/styled.ts
  src/pages/seller/[menu].tsx
  src/pages/seller/index.tsx
  src/shared/constants.ts
  src/styles/App.style.ts
  src/styles/GlobalStyle.ts
  src/utils/ImageWrapper.ts
Labels: 세팅

#28 Feature/product details
  components/Buttons/styled.ts
  components/ReviewItem/index.tsx
  components/ReviewItem/styled.ts
  components/StarRating/index.tsx
  pages/products/[id]/index.tsx
  pages/products/[id]/styled.ts
  public/images/icon-triangle-downward.svg
  public/images/icon-triangle-upward.svg
Labels: 기능 추가

#47 🐛 input 컴포넌트 버그 수정
  components/Inputs/index.tsx
Labels: 버그 수정

#42 상품등록 page UI 구현 및 tinyMCE 에디터 적용
  components/layouts/SellerLayout.tsx
  package.json
  pages/addproduct/index.tsx
  public/images/img-button.png
  styles/GlobalStyle.ts
  yarn.lock
Labels: 기능 추가

#51 🔧 @components의 PATH 변경
  tsconfig.json
Labels: 세팅

#55 동적인 TabMenu와 PriceCalculator 컴포넌트 구현 및 src 폴더로 이동
  components/Buttons/index.tsx
  components/Buttons/styled.ts
  components/ReviewItem/index.tsx
  components/ReviewItem/styled.ts
  components/StarRating/index.tsx
  components/index.ts
  pages/products/[id]/index.tsx
  pages/products/[id]/styled.ts
  public/images/icon-minus-line.svg
  public/images/icon-plus-line.svg
  src/components/Buttons/styled.ts
  src/components/PriceCalculator/index.tsx
  src/components/PriceCalculator/styled.ts
  src/components/ReviewItem/index.tsx
  src/components/ReviewItem/styled.ts
  src/components/StarRating/index.tsx
  src/components/TabMenu/index.tsx
  src/components/TabMenu/styled.ts
  src/components/index.ts
  src/pages/products/[id]/index.tsx
  src/pages/products/[id]/styled.ts
Labels: 기능 추가

#57 제품 상세 페이지 기능에 필요한 컴포넌트 구현
  public/images/icon-caret-next.svg
  public/images/icon-caret-prev.svg
  public/images/product-img-small-1.png
  public/images/product-img-small-2.png
  public/images/product-img-small-3.png
  public/images/product-img-small-4.png
  public/images/product-img-small-5.png
  src/components/CommentItem/index.tsx
  src/components/CommentItem/styled.ts
  src/components/CommentList/dummyCommentsData.json
  src/components/CommentList/index.tsx
  src/components/CommentList/styled.ts
  src/components/Pagination/index.tsx
  src/components/Pagination/styled.ts
  src/components/PriceCalculator/index.tsx
  src/components/ProductImage/index.tsx
  src/components/ProductImage/styled.ts
  src/components/ReviewItem/index.tsx
  src/components/ReviewItem/styled.ts
  src/components/ReviewList/index.tsx
  src/components/ReviewList/styled.ts
  src/components/index.ts
  src/pages/products/[id]/dummyProductData.json
  src/pages/products/[id]/index.tsx
  src/pages/products/[id]/styled.ts
Labels: 기능 추가
